port: 8081

nacos:
  serviceName: tiktok.simple.video
  addr: 101.43.5.142
  port: 8848
  username: nacos
  password: nacos

minio:
  AccessKeyId: "minioadmin"
  SecretAccessKey: "minioadmin"

mysql:
  dsn: root2:root1234@tcp(101.43.5.142:3306)/tiktok_vms?charset=utf8&parseTime=True&loc=Local

rabbitmq:
  url: amqp://guest:guest@120.25.2.146:5672/