version: "3"

services:
  tiktok_gateway:
    container_name: tiktok_gateway
    image: gateway
    ports:
      - "8070:8070"
    restart: always
  tiktok_user:
    container_name: tiktok_user
    image: user
    ports:
      - "8080:8080"
    restart: always
  tiktok_video:
    container_name: tiktok_video
    image: video
    ports:
      - "8081:8081"
    restart: always