// Code generated by hertz generator.

package handler

import (
	"TIKTOK_Video/model/vo"
	"TIKTOK_Video/service/Imp"
	"context"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserInfo

// Demo structure

/*
视频流接口
*/

func Feed(ctx context.Context, c *app.RequestContext) {
	//inputTime := c.Query("latest_time")
	var lastTime time.Time
	// TODO:这里需要token判断是否登入
	/**
		if inputTime != "0" {
		me, _ := strconv.ParseInt(inputTime, 10, 64)
		lastTime = time.Unix(me, 0)
	} else {
		lastTime = time.Now()
	}
	*/
	lastTime = time.Now()
	log.Printf("获取到时间戳%v", lastTime)
	VideoFeedService := Imp.VideoFeedServiceImpl{}
	feed, nextTime, err := VideoFeedService.GetVideoByLatestTime(lastTime)
	if err != nil {
		log.Printf("方法videoService.Feed(lastTime, userId) 失败：%v", err)
		c.JSON(http.StatusOK, vo.FeedResponse{
			StatusCode: 1,
			StatusMsg:  "获取视频流失败",
		})
		return
	}
	fmt.Println(feed[0].PlayUrl)
	c.JSON(consts.StatusOK, vo.FeedResponse{
		StatusCode: 0,
		StatusMsg:  " ok",
		VideoList:  feed,
		NextTime:   nextTime.Unix(),
	})
}

/*
	评论操作接口
*/
