port: 8080

nacos:
  serviceName: tiktok.simple.user
  addr: 101.42.50.112
  port: 8845
  username: nacos
  password: nacos

mysql:
  dsn: root1:root1234@tcp(120.25.2.146:3306)/tiktok_ums?charset=utf8&parseTime=True&loc=Local