port: 8070

nacos:
  addr: 101.43.5.142
  port: 8848

routes:
  - serviceName: http://tiktok.simple.user
    method: GET
    apis:
      - /douyin/user/
      - /douyin/publish/list/
      - /douyin/favorite/list/
      - /douyin/relation/follow/list/
      - /douyin/relation/follower/list/
      - /douyin/relation/friend/list/
      - /douyin/favorite/IsFavor/
      - /douyin/message/chat/

  - serviceName: http://tiktok.simple.user
    method: POST
    apis:
      - /douyin/user/register/
      - /douyin/user/login/
      - /douyin/favorite/action/
      - /douyin/relation/action/
      - /douyin/publish/UserVideo/
      - /douyin/message/action/

  - serviceName: http://tiktok.simple.video
    method: GET
    apis:
      - /douyin/feed/
      - /douyin/comment/list/


  - serviceName: http://tiktok.simple.video
    method: POST
    apis:
      - /douyin/comment/action/
      - /douyin/publish/action/
      - /douyin/publish/GetVideos/